'use client'

import { Button } from '@/components/ui/button'
import { Printer } from 'lucide-react'

interface PrintableEvent {
  patientAlias: string
  dobMonthYear?: string | null
  diagnosis: string
  hospitalName: string
  admissionDate: string
  admissionTime?: string | null
  dischargeDate?: string | null
  dischargeTime?: string | null
  dischargeNotes?: string | null
  status: string
}

export function PrintButton({ event }: { event: PrintableEvent }) {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    const admDate = new Date(event.admissionDate).toLocaleDateString()
    const disDate = event.dischargeDate ? new Date(event.dischargeDate).toLocaleDateString() : null

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Patient Report - ${event.patientAlias}</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #333; }
            h1 { color: #0369a1; border-bottom: 2px solid #0369a1; padding-bottom: 10px; }
            .field { margin: 12px 0; }
            .field-label { font-weight: bold; font-size: 12px; text-transform: uppercase; color: #666; }
            .field-value { font-size: 16px; margin-top: 4px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 20px 0; }
            .notes { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-top: 20px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; }
            @media print { body { margin: 20px; } }
          </style>
        </head>
        <body>
          <h1>TOCdoctor.com — Patient Report</h1>
          <div class="grid">
            <div class="field">
              <div class="field-label">Patient Name/ID</div>
              <div class="field-value">${event.patientAlias}</div>
            </div>
            <div class="field">
              <div class="field-label">Date of Birth</div>
              <div class="field-value">${event.dobMonthYear || 'N/A'}</div>
            </div>
            <div class="field">
              <div class="field-label">Hospital / Facility</div>
              <div class="field-value">${event.hospitalName}</div>
            </div>
            <div class="field">
              <div class="field-label">Status</div>
              <div class="field-value">${event.status}</div>
            </div>
            <div class="field">
              <div class="field-label">Admission Date</div>
              <div class="field-value">${admDate}${event.admissionTime ? ' at ' + event.admissionTime : ''}</div>
            </div>
            ${disDate ? `
            <div class="field">
              <div class="field-label">Discharge Date</div>
              <div class="field-value">${disDate}${event.dischargeTime ? ' at ' + event.dischargeTime : ''}</div>
            </div>
            ` : ''}
          </div>
          <div class="field">
            <div class="field-label">Diagnosis</div>
            <div class="field-value">${event.diagnosis}</div>
          </div>
          ${event.dischargeNotes ? `
          <div class="notes">
            <div class="field-label">Discharge Notes</div>
            <div class="field-value" style="white-space: pre-wrap;">${event.dischargeNotes}</div>
          </div>
          ` : ''}
          <div class="footer">
            Generated by TOCdoctor.com on ${new Date().toLocaleString()}<br/>
            This document contains protected health information. Handle in accordance with HIPAA regulations.
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => printWindow.print(), 250)
  }

  return (
    <Button variant="ghost" size="sm" onClick={handlePrint} title="Print report">
      <Printer className="h-4 w-4" />
    </Button>
  )
}
